class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def set_state_list
    @state_list = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"]
  end

  def state_from_abbrev(state)
    case state
    when "AL"
      return "Alabama"
    when "AK"
      return "Alaska"
    when "AL"
      return "Alabama"
    when "AR"
      return "Arkansas"
    when "AZ"
      return "Arizona"
    when "CA"
      return "California"
    when "CO"
      return "Colorado"
    when "CT"
      return "Connecticut"
    when "DE"
      return "Delaware"
    when "FL"
      return "Florida"
    when "GA"
      return "Georgia"
    when "HI"
      return "Hawaii"
    when "IA"
      return "Iowa"
    when "ID"
      return "Idaho"
    when "IL"
      return "Illinois"
    when "IN"
      return "Indiana"
    when "KS"
      return "Kansas"
    when "KY"
      return "Kentucky"
    when "LA"
      return "Louisiana"
    when "MA"
      return "Massachusetts"
    when "MD"
      return "Maryland"
    when "ME"
      return "Maine"
    when "MI"
      return "Michigan"
    when "MN"
      return "Minnesota"
    when "MO"
      return "Missouri"
    when "MS"
      return "Mississippi"
    when "MT"
      return "Montana"
    when "NC"
      return "North Carolina"
    when "ND"
      return "North Dakota"
    when "NE"
      return "Nebraska"
    when "NH"
      return "New Hampshire"
    when "NJ"
      return "New Jersey"
    when "NM"
      return "New Mexico"
    when "NV"
      return "Nevada"
    when "NY"
      return "New York"
    when "OH"
      return "Ohio"
    when "OK"
      return "Oklahoma"
    when "OR"
      return "Oregon"
    when "PA"
      return "Pennsylvania"
    when "RI"
      return "Rhode Island"
    when "SC"
      return "South Carolina"
    when "SD"
      return "South Dakota"
    when "TN"
      return "Tennessee"
    when "TX"
      return "Texas"
    when "UT"
      return "Utah"
    when "VA"
      return "Virginia"
    when "VT"
      return "Vermont"
    when "WA"
      return "Washington"
    when "WI"
      return "Wisconsin"
    when "WV"
      return "West Virginia"
    when "WY"
      return "Wyoming"
    end
  end

end
